version: "3.8"

services:
  back-end:
    build:
      context: ./back-end  
      dockerfile: Dockerfile
    container_name: golang-api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: 'postgres://postgres:Testing12345@db:5432/postgres?sslmode=disable'
      STRIPE_WEBHOOK_URL: "http://stripe-webhook:3000/api/webhook"
    ports:
      - 8080:8080
    volumes:
      - ./back-end/:/app
    networks:
      - app_network

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'Testing12345'
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/initDB.sql:/docker-entrypoint-initdb.d/initDB.sql
    ports:
      - 5432:5432
    networks:
      - app_network

  front-end:
    build:
      context: ./front-end 
      dockerfile: Dockerfile
    container_name: nextjs-front-end
    depends_on:
      - back-end
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:8080"
    ports:
      - 3000:3000
    volumes:
      - ./front-end:/app
      - /app/node_modules
    networks:
      - app_network

  stripe-webhook:
    image: stripe/stripe-cli
    container_name: stripe-webhook
    command: ["listen", "--forward-to", "front-end:3000/api/42a53b71-7fc8-4644-a6e3-3fe2c0c03443/webhook"]
    env_file:
    - ./front-end/.env
    environment:
      STRIPE_API_KEY: ${STRIPE_API_KEY}
    depends_on:
      - front-end
    networks:
      - app_network
    ports:
      - 3001:3001

networks:
  app_network:
    driver: bridge
    external: true

volumes:
  postgres_data:
